### PR TITLE
Support send grid api credentials specification for a specific mail. 

### PR DESCRIPTION
**Pull request by nfornaro**
Needed if an application needs to use more than one sendgrid account.

### CODE REVIEW

**Comment by antony** [comment]
Looks good to me - thanks!

**Comment by nfornaro** [comment]
Hi Antony,

Do you think we could move to version 1.4 in grails repo? It would be nice so we can easily upgrade several projects.

Regards

Nicolás

**Comment by antony** [comment]
Hi Nicolas,

I tried to deploy it last night - I can't even get grails to publish a new release. I gave up after about an hour of trying. I'll give it another go as soon as I have some time.

Sorry about that!

**Comment by nfornaro** [comment]
No problem, thank you!

**Pull request merged**
